<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>05e1753c-e7db-4f30-b951-5a4e052d1d36</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Payment.Application\Restaurant.Payment.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Payment.Data\Restaurant.Payment.Data.csproj" />
    <ProjectReference Include="..\Restaurant.Payment.ExternalServices\Restaurant.Payment.ExternalServices.csproj" />
    <ProjectReference Include="..\Restaurant.Payment.Facade\Restaurant.Payment.Facade.csproj" />
    <ProjectReference Include="..\Restaurant.Payment.Presenter\Restaurant.Payment.Presenter.csproj" />
  </ItemGroup>

</Project>
