<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Presenters\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Payment.Application\Restaurant.Payment.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Payment.Data\Restaurant.Payment.Data.csproj" />
  </ItemGroup>

</Project>
